platform :ios, '8.0'

target 'HealthManager' do
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage' ,'~>3.7.5'
pod 'SVProgressHUD', '~>2.1.2'
pod 'MJExtension'
pod 'MJRefresh'
pod 'FMDB'
pod 'Masonry'
pod 'ChameleonFramework', '~> 2.1.0'
pod 'PNChart'
pod 'YBPopupMenu'
end
